"""empty message

Revision ID: 79773b8d1b11
Revises: 102c55e32031
Create Date: 2020-05-12 10:58:51.601092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79773b8d1b11'
down_revision = '102c55e32031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
